backend:
  name: github
  repo: gustavpursche/cifar
  branch: develop

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Report"
        name: "report"
        file: "data/pages/report.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Text"
            name: "body"
            widget: "markdown"

      - label: "Home"
        name: "home"
        file: "data/pages/home.md"
        fields:
          - label: Title
            name: title
            widget: string

          - label: "Mission statement"
            name: "missionStatement"
            widget: "markdown"

  - name: "countries"
    label: "Countries"
    folder: "data/countries"
    create: true
    preview: false
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "title"
        widget: "string"

      - label: "Summary"
        name: "summary"
        widget: "markdown"

  - name: "persons"
    label: "Persons"
    folder: "data/persons"
    create: true
    preview: false
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "title"
        widget: "string"

      - label: "Name in native language"
        name: "nameNative"
        widget: "string"
        required: false

      - label: "Identifying information"
        name: "role"
        widget: "string"

      - label: "Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Ancestor"
        name: "ancestor"
        widget: "relation"
        collection: "persons"
        searchFields: ["title"]
        valueField: "title"
        required: false

      - label: "Connection to ancestor"
        name: "connection"
        widget: "select"
        options:
          - { label: "Family", value: "family" }
          - { label: "Government", value: "government" }
          - { label: "Private sector", value: "business" }
        required: false

      - label: "Aliases"
        name: "aliases"
        widget: "list"
        field:
          - label: "Name"
            name: "name"
            widget: "string"
        required: false

      - label: "Country"
        name: "country"
        widget: "select"
        options:
          - { label: "Egypt", value: "Egypt" }
          - { label: "Tunesia", value: "Tunesia" }
          - { label: "Ukraine", value: "Ukraine" }

      - label: "Suspected or confirmed overseas properties"
        name: "overseasProperties"
        widget: "string"
        required: false

      - label: "Suspected or confirmed links to companies"
        name: "linkedCompanies"
        widget: "string"
        required: false

      - label: "Estimate of total stolen assets"
        name: "stolenAssets"
        widget: "string"
        required: false

      - label: "Estimates of assets frozen or confiscated"
        name: "frozenAssets"
        widget: "string"
        required: false

      - label: "Country of origin"
        name: "originCountry"
        widget: "string"
        required: false

      - label: "City of origin"
        name: "originCity"
        widget: "string"
        required: false

      - label: "Birthdate"
        name: "birthdate"
        widget: "date"
        required: false

      - label: "Gender"
        name: "gender"
        widget: "string"
        required: false

      - label: "Grounds for sanctions"
        name: "groundsForSanctions"
        widget: "string"
        required: false

      - label: "Intro"
        name: "body"
        widget: "markdown"
        required: false

media_folder: "static/media/uploads"
